/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
import { Candid } "mo:serde-core";
import Array "mo:core/Array";
import List "mo:core/List";
import Float "mo:core/Float";
import Runtime "mo:core/Runtime";

// ChatCompletionRequestAssistantMessageFunctionCall.mo

module {
    /// The required-fields slice of ChatCompletionRequestAssistantMessageFunctionCall — what `init` consumes.
    /// Exposed so callers can write `let req : Required = {...}` if they want
    /// to manipulate the required-only payload independently of the full record.
    public type Required = {
        /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
        arguments : Text;
        /// The name of the function to call.
        name : Text;
    };

    // Optional-fields slice. Private — not part of the consumer surface;
    // it's an internal scaffold so we can express ChatCompletionRequestAssistantMessageFunctionCall as an
    // `and`-intersection and keep `init` from listing every optional explicitly.
    type Optional = {
    };

    public type ChatCompletionRequestAssistantMessageFunctionCall = Required and Optional;

    public module JSON {
        // `init` constructs a ChatCompletionRequestAssistantMessageFunctionCall from just its required fields,
        // defaulting all optional fields to `null`. Pair with record-update
        // syntax to layer in selected optionals:
        //   let req = { ChatCompletionRequestAssistantMessageFunctionCall.init { …required fields… } with someOpt = ?… };
        // Implementation uses Candid round-trip — Candid record subtyping fills
        // absent optional fields with null. Costs a few cycles per call (init is
        // not on a hot path) but keeps generated code compact regardless of how
        // many optional fields the model has.
        public func init(required : Required) : ChatCompletionRequestAssistantMessageFunctionCall {
            let ?res = from_candid(to_candid(required)) : ?ChatCompletionRequestAssistantMessageFunctionCall else Runtime.unreachable();
            res
        };

        public func toCandidValue(value : ChatCompletionRequestAssistantMessageFunctionCall) : Candid.Candid {
            let buf = List.empty<(Text, Candid.Candid)>();
            List.add(buf, ("arguments", #Text(value.arguments)));
            List.add(buf, ("name", #Text(value.name)));
            #Record(List.toArray(buf));
        };

        public func fromCandidValue(candid : Candid.Candid) : ?ChatCompletionRequestAssistantMessageFunctionCall =
            switch (candid) {
                case (#Record(fields)) {
                    let ?arguments_field = Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "arguments") else return null;
                    let ?arguments = ((switch (arguments_field.1) { case (#Text(s)) ?s; case _ null })) else return null;
                    let ?name_field = Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "name") else return null;
                    let ?name = ((switch (name_field.1) { case (#Text(s)) ?s; case _ null })) else return null;
                    ?{
                        arguments;
                        name;
                    };
                };
                case _ null;
            };
    };
};
