
import { type ChatCompletionMessageToolCall; JSON = ChatCompletionMessageToolCall } "./ChatCompletionMessageToolCall";

import { type ChatCompletionResponseMessageAnnotationsInner; JSON = ChatCompletionResponseMessageAnnotationsInner } "./ChatCompletionResponseMessageAnnotationsInner";

import { type ChatCompletionResponseMessageAudio; JSON = ChatCompletionResponseMessageAudio } "./ChatCompletionResponseMessageAudio";

import { type ChatCompletionResponseMessageFunctionCall; JSON = ChatCompletionResponseMessageFunctionCall } "./ChatCompletionResponseMessageFunctionCall";

import { type ChatCompletionResponseMessageRole; JSON = ChatCompletionResponseMessageRole } "./ChatCompletionResponseMessageRole";
import { Candid } "mo:serde-core";
import Array "mo:core/Array";
import List "mo:core/List";
import Float "mo:core/Float";

// ChatCompletionMessageListDataInner.mo

module {
    public type ChatCompletionMessageListDataInner = {
        /// The contents of the message.
        content : ?Text;
        /// The refusal message generated by the model.
        refusal : ?Text;
        /// The tool calls generated by the model, such as function calls.
        tool_calls : ?[ChatCompletionMessageToolCall];
        /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat). 
        annotations : ?[ChatCompletionResponseMessageAnnotationsInner];
        role : ChatCompletionResponseMessageRole;
        function_call : ?ChatCompletionResponseMessageFunctionCall;
        audio : ?ChatCompletionResponseMessageAudio;
        /// The identifier of the chat message.
        id : Text;
    };

    public module JSON {
        public func toCandidValue(value : ChatCompletionMessageListDataInner) : Candid.Candid {
            let buf = List.empty<(Text, Candid.Candid)>();
            switch (value.content) {
                case (?v__) List.add(buf, ("content", #Text(v__)));
                case null ();
            };
            switch (value.refusal) {
                case (?v__) List.add(buf, ("refusal", #Text(v__)));
                case null ();
            };
            switch (value.tool_calls) {
                case (?v__) List.add(buf, ("tool_calls", #Array(Array.map<ChatCompletionMessageToolCall, Candid.Candid>(v__, ChatCompletionMessageToolCall.toCandidValue))));
                case null ();
            };
            switch (value.annotations) {
                case (?v__) List.add(buf, ("annotations", #Array(Array.map<ChatCompletionResponseMessageAnnotationsInner, Candid.Candid>(v__, ChatCompletionResponseMessageAnnotationsInner.toCandidValue))));
                case null ();
            };
            List.add(buf, ("role", ChatCompletionResponseMessageRole.toCandidValue(value.role)));
            switch (value.function_call) {
                case (?v__) List.add(buf, ("function_call", ChatCompletionResponseMessageFunctionCall.toCandidValue(v__)));
                case null ();
            };
            switch (value.audio) {
                case (?v__) List.add(buf, ("audio", ChatCompletionResponseMessageAudio.toCandidValue(v__)));
                case null ();
            };
            List.add(buf, ("id", #Text(value.id)));
            #Record(List.toArray(buf));
        };

        public func fromCandidValue(candid : Candid.Candid) : ?ChatCompletionMessageListDataInner =
            switch (candid) {
                case (#Record(fields)) {
                    let content : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "content")) {
                        case (?content_field) ((switch (content_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let refusal : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "refusal")) {
                        case (?refusal_field) ((switch (refusal_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let tool_calls : ?[ChatCompletionMessageToolCall] = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "tool_calls")) {
                        case (?tool_calls_field) ((switch (tool_calls_field.1) {
                        case (#Array(xs__)) {
                            let buf__ = List.empty<ChatCompletionMessageToolCall>();
                            for (c__ in xs__.values()) {
                                let ?m__ = ChatCompletionMessageToolCall.fromCandidValue(c__) else return null;
                                List.add(buf__, m__);
                            };
                            ?List.toArray(buf__);
                        };
                        case _ null;
                    }));
                        case null null;
                    };
                    let annotations : ?[ChatCompletionResponseMessageAnnotationsInner] = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "annotations")) {
                        case (?annotations_field) ((switch (annotations_field.1) {
                        case (#Array(xs__)) {
                            let buf__ = List.empty<ChatCompletionResponseMessageAnnotationsInner>();
                            for (c__ in xs__.values()) {
                                let ?m__ = ChatCompletionResponseMessageAnnotationsInner.fromCandidValue(c__) else return null;
                                List.add(buf__, m__);
                            };
                            ?List.toArray(buf__);
                        };
                        case _ null;
                    }));
                        case null null;
                    };
                    let ?role_field = Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "role") else return null;
                    let ?role = (ChatCompletionResponseMessageRole.fromCandidValue(role_field.1)) else return null;
                    let function_call : ?ChatCompletionResponseMessageFunctionCall = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "function_call")) {
                        case (?function_call_field) (ChatCompletionResponseMessageFunctionCall.fromCandidValue(function_call_field.1));
                        case null null;
                    };
                    let audio : ?ChatCompletionResponseMessageAudio = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "audio")) {
                        case (?audio_field) (ChatCompletionResponseMessageAudio.fromCandidValue(audio_field.1));
                        case null null;
                    };
                    let ?id_field = Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "id") else return null;
                    let ?id = ((switch (id_field.1) { case (#Text(s)) ?s; case _ null })) else return null;
                    ?{
                        content;
                        refusal;
                        tool_calls;
                        annotations;
                        role;
                        function_call;
                        audio;
                        id;
                    };
                };
                case _ null;
            };
    };
};
