
import { type ChatCompletionMessageToolCall; JSON = ChatCompletionMessageToolCall } "./ChatCompletionMessageToolCall";

import { type ChatCompletionResponseMessageAnnotationsInner; JSON = ChatCompletionResponseMessageAnnotationsInner } "./ChatCompletionResponseMessageAnnotationsInner";

import { type ChatCompletionResponseMessageAudio; JSON = ChatCompletionResponseMessageAudio } "./ChatCompletionResponseMessageAudio";

import { type ChatCompletionResponseMessageFunctionCall; JSON = ChatCompletionResponseMessageFunctionCall } "./ChatCompletionResponseMessageFunctionCall";

import { type ChatCompletionResponseMessageRole; JSON = ChatCompletionResponseMessageRole } "./ChatCompletionResponseMessageRole";

// ChatCompletionMessageListDataInner.mo

module {
    // User-facing type: what application code uses
    public type ChatCompletionMessageListDataInner = {
        /// The contents of the message.
        content : Text;
        /// The refusal message generated by the model.
        refusal : Text;
        /// The tool calls generated by the model, such as function calls.
        tool_calls : ?[ChatCompletionMessageToolCall];
        /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat). 
        annotations : ?[ChatCompletionResponseMessageAnnotationsInner];
        role : ChatCompletionResponseMessageRole;
        function_call : ?ChatCompletionResponseMessageFunctionCall;
        audio : ?ChatCompletionResponseMessageAudio;
        /// The identifier of the chat message.
        id : Text;
    };

    // JSON sub-module: everything needed for JSON serialization
    public module JSON {
        // JSON-facing Motoko type: mirrors JSON structure
        // Named "JSON" to avoid shadowing the outer ChatCompletionMessageListDataInner type
        public type JSON = {
            content : Text;
            refusal : Text;
            tool_calls : ?[ChatCompletionMessageToolCall];
            annotations : ?[ChatCompletionResponseMessageAnnotationsInner];
            role : ChatCompletionResponseMessageRole.JSON;
            function_call : ?ChatCompletionResponseMessageFunctionCall;
            audio : ?ChatCompletionResponseMessageAudio;
            id : Text;
        };

        // Convert User-facing type to JSON-facing Motoko type
        public func toJSON(value : ChatCompletionMessageListDataInner) : JSON = { value with
            role = ChatCompletionResponseMessageRole.toJSON(value.role);
        };

        // Convert JSON-facing Motoko type to User-facing type
        public func fromJSON(json : JSON) : ?ChatCompletionMessageListDataInner {
            let ?role = ChatCompletionResponseMessageRole.fromJSON(json.role) else return null;
            ?{ json with
                role;
            }
        };
    }
}
