/// A chat completion message generated by the model.

import { type ChatCompletionMessageToolCall; JSON = ChatCompletionMessageToolCall } "./ChatCompletionMessageToolCall";

import { type ChatCompletionResponseMessageAnnotationsInner; JSON = ChatCompletionResponseMessageAnnotationsInner } "./ChatCompletionResponseMessageAnnotationsInner";

import { type ChatCompletionResponseMessageAudio; JSON = ChatCompletionResponseMessageAudio } "./ChatCompletionResponseMessageAudio";

import { type ChatCompletionResponseMessageFunctionCall; JSON = ChatCompletionResponseMessageFunctionCall } "./ChatCompletionResponseMessageFunctionCall";

import { type ChatCompletionResponseMessageRole; JSON = ChatCompletionResponseMessageRole } "./ChatCompletionResponseMessageRole";

// ChatCompletionResponseMessage.mo

module {
    // User-facing type: what application code uses
    public type ChatCompletionResponseMessage = {
        /// The contents of the message.
        content : Text;
        /// The refusal message generated by the model.
        refusal : Text;
        /// The tool calls generated by the model, such as function calls.
        tool_calls : ?[ChatCompletionMessageToolCall];
        /// Annotations for the message, when applicable, as when using the [web search tool](/docs/guides/tools-web-search?api-mode=chat). 
        annotations : ?[ChatCompletionResponseMessageAnnotationsInner];
        role : ChatCompletionResponseMessageRole;
        function_call : ?ChatCompletionResponseMessageFunctionCall;
        audio : ?ChatCompletionResponseMessageAudio;
    };

    // JSON sub-module: everything needed for JSON serialization
    public module JSON {
        // JSON-facing Motoko type: mirrors JSON structure
        // Named "JSON" to avoid shadowing the outer ChatCompletionResponseMessage type
        public type JSON = {
            content : Text;
            refusal : Text;
            tool_calls : ?[ChatCompletionMessageToolCall];
            annotations : ?[ChatCompletionResponseMessageAnnotationsInner];
            role : ChatCompletionResponseMessageRole.JSON;
            function_call : ?ChatCompletionResponseMessageFunctionCall;
            audio : ?ChatCompletionResponseMessageAudio;
        };

        // Convert User-facing type to JSON-facing Motoko type
        public func toJSON(value : ChatCompletionResponseMessage) : JSON = { value with
            role = ChatCompletionResponseMessageRole.toJSON(value.role);
        };

        // Convert JSON-facing Motoko type to User-facing type
        public func fromJSON(json : JSON) : ?ChatCompletionResponseMessage {
            let ?role = ChatCompletionResponseMessageRole.fromJSON(json.role) else return null;
            ?{ json with
                role;
            }
        };

        // Pre-flight validation (`diagnostics=true`): surface generator-known wire-format
        // gaps as `?Text`, so api.mustache can `throw Error.reject(msg)` instead of letting
        // bad JSON reach the upstream API and come back as an opaque 4xx.
        public func validate(_value : ChatCompletionResponseMessage) : ?Text = null;
    }
}
