/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.

// ChatCompletionResponseMessageFunctionCall.mo

module {
    // User-facing type: what application code uses
    public type ChatCompletionResponseMessageFunctionCall = {
        /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
        arguments : Text;
        /// The name of the function to call.
        name : Text;
    };

    // JSON sub-module: everything needed for JSON serialization
    public module JSON {
        // JSON-facing Motoko type: mirrors JSON structure
        // Named "JSON" to avoid shadowing the outer ChatCompletionResponseMessageFunctionCall type
        public type JSON = {
            arguments : Text;
            name : Text;
        };

        // Convert User-facing type to JSON-facing Motoko type
        public func toJSON(value : ChatCompletionResponseMessageFunctionCall) : JSON = value;

        // Convert JSON-facing Motoko type to User-facing type
        public func fromJSON(json : JSON) : ?ChatCompletionResponseMessageFunctionCall = ?json;
    }
}
