/// A chat completion delta generated by streamed model responses.

import { type ChatCompletionMessageToolCallChunk; JSON = ChatCompletionMessageToolCallChunk } "./ChatCompletionMessageToolCallChunk";

import { type ChatCompletionStreamResponseDeltaFunctionCall; JSON = ChatCompletionStreamResponseDeltaFunctionCall } "./ChatCompletionStreamResponseDeltaFunctionCall";

import { type ChatCompletionStreamResponseDeltaRole; JSON = ChatCompletionStreamResponseDeltaRole } "./ChatCompletionStreamResponseDeltaRole";

// ChatCompletionStreamResponseDelta.mo

module {
    // User-facing type: what application code uses
    public type ChatCompletionStreamResponseDelta = {
        /// The contents of the chunk message.
        content : ?Text;
        function_call : ?ChatCompletionStreamResponseDeltaFunctionCall;
        tool_calls : ?[ChatCompletionMessageToolCallChunk];
        role : ?ChatCompletionStreamResponseDeltaRole;
        /// The refusal message generated by the model.
        refusal : ?Text;
    };

    // JSON sub-module: everything needed for JSON serialization
    public module JSON {
        // JSON-facing Motoko type: mirrors JSON structure
        // Named "JSON" to avoid shadowing the outer ChatCompletionStreamResponseDelta type
        public type JSON = {
            content : ?Text;
            function_call : ?ChatCompletionStreamResponseDeltaFunctionCall;
            tool_calls : ?[ChatCompletionMessageToolCallChunk];
            role : ?ChatCompletionStreamResponseDeltaRole.JSON;
            refusal : ?Text;
        };

        // Convert User-facing type to JSON-facing Motoko type
        public func toJSON(value : ChatCompletionStreamResponseDelta) : JSON = { value with
            role = do ? { ChatCompletionStreamResponseDeltaRole.toJSON(value.role!) };
        };

        // Convert JSON-facing Motoko type to User-facing type
        public func fromJSON(json : JSON) : ?ChatCompletionStreamResponseDelta {
            ?{ json with
                role = do ? { ChatCompletionStreamResponseDeltaRole.fromJSON(json.role!)! };
            }
        };
    }
}
