/// Messages sent by the model in response to user messages. 

import { type ChatCompletionMessageToolCall; JSON = ChatCompletionMessageToolCall } "./ChatCompletionMessageToolCall";

import { type ChatCompletionRequestAssistantMessageAudio; JSON = ChatCompletionRequestAssistantMessageAudio } "./ChatCompletionRequestAssistantMessageAudio";

import { type ChatCompletionRequestAssistantMessageContent; JSON = ChatCompletionRequestAssistantMessageContent } "./ChatCompletionRequestAssistantMessageContent";

import { type ChatCompletionRequestAssistantMessageFunctionCall; JSON = ChatCompletionRequestAssistantMessageFunctionCall } "./ChatCompletionRequestAssistantMessageFunctionCall";

import { type ChatCompletionRequestAssistantMessageRole; JSON = ChatCompletionRequestAssistantMessageRole } "./ChatCompletionRequestAssistantMessageRole";

// ChatCompletionRequestAssistantMessage.mo

module {
    // User-facing type: what application code uses
    public type ChatCompletionRequestAssistantMessage = {
        content : ?ChatCompletionRequestAssistantMessageContent;
        /// The refusal message by the assistant.
        refusal : ?Text;
        role : ChatCompletionRequestAssistantMessageRole;
        /// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
        name : ?Text;
        audio : ?ChatCompletionRequestAssistantMessageAudio;
        /// The tool calls generated by the model, such as function calls.
        tool_calls : ?[ChatCompletionMessageToolCall];
        function_call : ?ChatCompletionRequestAssistantMessageFunctionCall;
    };

    // JSON sub-module: everything needed for JSON serialization
    public module JSON {
        // JSON-facing Motoko type: mirrors JSON structure
        // Named "JSON" to avoid shadowing the outer ChatCompletionRequestAssistantMessage type
        public type JSON = {
            content : ?ChatCompletionRequestAssistantMessageContent;
            refusal : ?Text;
            role : ChatCompletionRequestAssistantMessageRole.JSON;
            name : ?Text;
            audio : ?ChatCompletionRequestAssistantMessageAudio;
            tool_calls : ?[ChatCompletionMessageToolCall];
            function_call : ?ChatCompletionRequestAssistantMessageFunctionCall;
        };

        // Convert User-facing type to JSON-facing Motoko type
        public func toJSON(value : ChatCompletionRequestAssistantMessage) : JSON = { value with
            role = ChatCompletionRequestAssistantMessageRole.toJSON(value.role);
        };

        // Convert JSON-facing Motoko type to User-facing type
        public func fromJSON(json : JSON) : ?ChatCompletionRequestAssistantMessage {
            let ?role = ChatCompletionRequestAssistantMessageRole.fromJSON(json.role) else return null;
            ?{ json with
                role;
            }
        };
    }
}
