/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
import { Candid } "mo:serde-core";
import Array "mo:core/Array";
import List "mo:core/List";
import Float "mo:core/Float";

// ChatCompletionStreamResponseDeltaFunctionCall.mo

module {
    public type ChatCompletionStreamResponseDeltaFunctionCall = {
        /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
        arguments : ?Text;
        /// The name of the function to call.
        name : ?Text;
    };

    public module JSON {
        public func toCandidValue(value : ChatCompletionStreamResponseDeltaFunctionCall) : Candid.Candid {
            let buf = List.empty<(Text, Candid.Candid)>();
            switch (value.arguments) {
                case (?v__) List.add(buf, ("arguments", #Text(v__)));
                case null ();
            };
            switch (value.name) {
                case (?v__) List.add(buf, ("name", #Text(v__)));
                case null ();
            };
            #Record(List.toArray(buf));
        };

        public func fromCandidValue(candid : Candid.Candid) : ?ChatCompletionStreamResponseDeltaFunctionCall =
            switch (candid) {
                case (#Record(fields)) {
                    let arguments : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "arguments")) {
                        case (?arguments_field) ((switch (arguments_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let name : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "name")) {
                        case (?name_field) ((switch (name_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    ?{
                        arguments;
                        name;
                    };
                };
                case _ null;
            };
    };
};
