
import { type ChatCompletionRequestMessageContentPartRefusalType; JSON = ChatCompletionRequestMessageContentPartRefusalType } "./ChatCompletionRequestMessageContentPartRefusalType";

// ChatCompletionRequestMessageContentPartRefusal.mo

module {
    // User-facing type: what application code uses
    public type ChatCompletionRequestMessageContentPartRefusal = {
        type_ : ChatCompletionRequestMessageContentPartRefusalType;
        /// The refusal message generated by the model.
        refusal : Text;
    };

    // JSON sub-module: everything needed for JSON serialization
    public module JSON {
        // JSON-facing Motoko type: mirrors JSON structure
        // Named "JSON" to avoid shadowing the outer ChatCompletionRequestMessageContentPartRefusal type
        public type JSON = {
            type_ : ChatCompletionRequestMessageContentPartRefusalType.JSON;
            refusal : Text;
        };

        // Convert User-facing type to JSON-facing Motoko type
        public func toJSON(value : ChatCompletionRequestMessageContentPartRefusal) : JSON = { value with
            type_ = ChatCompletionRequestMessageContentPartRefusalType.toJSON(value.type_);
        };

        // Convert JSON-facing Motoko type to User-facing type
        public func fromJSON(json : JSON) : ?ChatCompletionRequestMessageContentPartRefusal {
            let ?type_ = ChatCompletionRequestMessageContentPartRefusalType.fromJSON(json.type_) else return null;
            ?{ json with
                type_;
            }
        };
    }
}
