/// A chat completion delta generated by streamed model responses.

import { type ChatCompletionMessageToolCallChunk; JSON = ChatCompletionMessageToolCallChunk } "./ChatCompletionMessageToolCallChunk";

import { type ChatCompletionStreamResponseDeltaFunctionCall; JSON = ChatCompletionStreamResponseDeltaFunctionCall } "./ChatCompletionStreamResponseDeltaFunctionCall";

import { type ChatCompletionStreamResponseDeltaRole; JSON = ChatCompletionStreamResponseDeltaRole } "./ChatCompletionStreamResponseDeltaRole";
import { Candid } "mo:serde-core";
import Array "mo:core/Array";
import List "mo:core/List";

// ChatCompletionStreamResponseDelta.mo

module {
    public type ChatCompletionStreamResponseDelta = {
        /// The contents of the chunk message.
        content : ?Text;
        function_call : ?ChatCompletionStreamResponseDeltaFunctionCall;
        tool_calls : ?[ChatCompletionMessageToolCallChunk];
        role : ?ChatCompletionStreamResponseDeltaRole;
        /// The refusal message generated by the model.
        refusal : ?Text;
    };

    public module JSON {
        public func toCandidValue(value : ChatCompletionStreamResponseDelta) : Candid.Candid {
            let buf = List.empty<(Text, Candid.Candid)>();
            switch (value.content) {
                case (?v__) List.add(buf, ("content", #Text(v__)));
                case null ();
            };
            switch (value.function_call) {
                case (?v__) List.add(buf, ("function_call", ChatCompletionStreamResponseDeltaFunctionCall.toCandidValue(v__)));
                case null ();
            };
            switch (value.tool_calls) {
                case (?v__) List.add(buf, ("tool_calls", #Array(Array.map<ChatCompletionMessageToolCallChunk, Candid.Candid>(v__, ChatCompletionMessageToolCallChunk.toCandidValue))));
                case null ();
            };
            switch (value.role) {
                case (?v__) List.add(buf, ("role", ChatCompletionStreamResponseDeltaRole.toCandidValue(v__)));
                case null ();
            };
            switch (value.refusal) {
                case (?v__) List.add(buf, ("refusal", #Text(v__)));
                case null ();
            };
            #Record(List.toArray(buf));
        };

        public func fromCandidValue(candid : Candid.Candid) : ?ChatCompletionStreamResponseDelta =
            switch (candid) {
                case (#Record(fields)) {
                    let content : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "content")) {
                        case (?content_field) ((switch (content_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let function_call : ?ChatCompletionStreamResponseDeltaFunctionCall = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "function_call")) {
                        case (?function_call_field) (ChatCompletionStreamResponseDeltaFunctionCall.fromCandidValue(function_call_field.1));
                        case null null;
                    };
                    let tool_calls : ?[ChatCompletionMessageToolCallChunk] = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "tool_calls")) {
                        case (?tool_calls_field) ((switch (tool_calls_field.1) {
                        case (#Array(xs__)) {
                            let buf__ = List.empty<ChatCompletionMessageToolCallChunk>();
                            for (c__ in xs__.values()) {
                                let ?m__ = ChatCompletionMessageToolCallChunk.fromCandidValue(c__) else return null;
                                List.add(buf__, m__);
                            };
                            ?List.toArray(buf__);
                        };
                        case _ null;
                    }));
                        case null null;
                    };
                    let role : ?ChatCompletionStreamResponseDeltaRole = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "role")) {
                        case (?role_field) (ChatCompletionStreamResponseDeltaRole.fromCandidValue(role_field.1));
                        case null null;
                    };
                    let refusal : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "refusal")) {
                        case (?refusal_field) ((switch (refusal_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    ?{
                        content;
                        function_call;
                        tool_calls;
                        role;
                        refusal;
                    };
                };
                case _ null;
            };
    };
};
