/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
import { Candid } "mo:serde-core";
import Array "mo:core/Array";
import List "mo:core/List";
import Float "mo:core/Float";
import Runtime "mo:core/Runtime";

// ChatCompletionStreamResponseDeltaFunctionCall.mo

module {
    /// The required-fields slice of ChatCompletionStreamResponseDeltaFunctionCall — what `init` consumes.
    /// Exposed so callers can write `let req : Required = {...}` if they want
    /// to manipulate the required-only payload independently of the full record.
    public type Required = {
    };

    // Optional-fields slice. Private — not part of the consumer surface;
    // it's an internal scaffold so we can express ChatCompletionStreamResponseDeltaFunctionCall as an
    // `and`-intersection and keep `init` from listing every optional explicitly.
    type Optional = {
        arguments : ?Text;
        name : ?Text;
    };

    public type ChatCompletionStreamResponseDeltaFunctionCall = Required and Optional;

    public module JSON {
        // `init` constructs a ChatCompletionStreamResponseDeltaFunctionCall from just its required fields,
        // defaulting all optional fields to `null`. Pair with record-update
        // syntax to layer in selected optionals:
        //   let req = { ChatCompletionStreamResponseDeltaFunctionCall.init { …required fields… } with someOpt = ?… };
        // Implementation uses Candid round-trip — Candid record subtyping fills
        // absent optional fields with null. Costs a few cycles per call (init is
        // not on a hot path) but keeps generated code compact regardless of how
        // many optional fields the model has.
        public func init(required : Required) : ChatCompletionStreamResponseDeltaFunctionCall {
            let ?res = from_candid(to_candid(required)) : ?ChatCompletionStreamResponseDeltaFunctionCall else Runtime.unreachable();
            res
        };

        public func toCandidValue(value : ChatCompletionStreamResponseDeltaFunctionCall) : Candid.Candid {
            let buf = List.empty<(Text, Candid.Candid)>();
            switch (value.arguments) {
                case (?v__) List.add(buf, ("arguments", #Text(v__)));
                case null ();
            };
            switch (value.name) {
                case (?v__) List.add(buf, ("name", #Text(v__)));
                case null ();
            };
            #Record(List.toArray(buf));
        };

        public func fromCandidValue(candid : Candid.Candid) : ?ChatCompletionStreamResponseDeltaFunctionCall =
            switch (candid) {
                case (#Record(fields)) {
                    let arguments : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "arguments")) {
                        case (?arguments_field) ((switch (arguments_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let name : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "name")) {
                        case (?name_field) ((switch (name_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    ?{
                        arguments;
                        name;
                    };
                };
                case _ null;
            };
    };

    /// Re-export of `JSON.init` at the outer module level so callers using the
    /// whole-module import pattern (`import T "...";`) can write `T.init {…}`
    /// directly, mirroring the destructure-pattern (`{ type T; JSON = T }`)
    /// shorthand `T.init {…}` that resolves through the JSON alias.
    public let init = JSON.init;
};
