
import { type ChatCompletionStreamOptions; JSON = ChatCompletionStreamOptions } "./ChatCompletionStreamOptions";

import { type CreateCompletionRequestModel; JSON = CreateCompletionRequestModel } "./CreateCompletionRequestModel";

import { type CreateCompletionRequestPrompt; JSON = CreateCompletionRequestPrompt } "./CreateCompletionRequestPrompt";

import { type StopConfiguration; JSON = StopConfiguration } "./StopConfiguration";
import { type Map } "mo:core/pure/Map";

import Int "mo:core/Int";

// CreateCompletionRequest.mo

module {
    // User-facing type: what application code uses
    public type CreateCompletionRequest = {
        model : CreateCompletionRequestModel;
        prompt : CreateCompletionRequestPrompt;
        /// Generates `best_of` completions server-side and returns the \"best\" (the one with the highest log probability per token). Results cannot be streamed.  When used with `n`, `best_of` controls the number of candidate completions and `n` specifies how many to return – `best_of` must be greater than `n`.  **Note:** Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for `max_tokens` and `stop`. 
        best_of : ?Nat;
        /// Echo back the prompt in addition to the completion 
        echo : ?Bool;
        /// Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.  [See more information about frequency and presence penalties.](/docs/guides/text-generation) 
        frequency_penalty : ?Float;
        /// Modify the likelihood of specified tokens appearing in the completion.  Accepts a JSON object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this [tokenizer tool](/tokenizer?view=bpe) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.  As an example, you can pass `{\"50256\": -100}` to prevent the <|endoftext|> token from being generated. 
        logit_bias : ?Map<Text, Int>;
        /// Include the log probabilities on the `logprobs` most likely output tokens, as well the chosen tokens. For example, if `logprobs` is 5, the API will return a list of the 5 most likely tokens. The API will always return the `logprob` of the sampled token, so there may be up to `logprobs+1` elements in the response.  The maximum value for `logprobs` is 5. 
        logprobs : ?Nat;
        /// The maximum number of [tokens](/tokenizer) that can be generated in the completion.  The token count of your prompt plus `max_tokens` cannot exceed the model's context length. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens. 
        max_tokens : ?Nat;
        /// How many completions to generate for each prompt.  **Note:** Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for `max_tokens` and `stop`. 
        n : ?Nat;
        /// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.  [See more information about frequency and presence penalties.](/docs/guides/text-generation) 
        presence_penalty : ?Float;
        /// If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.  Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend. 
        seed : ?Int;
        stop : ?StopConfiguration;
        /// Whether to stream back partial progress. If set, tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://cookbook.openai.com/examples/how_to_stream_completions). 
        stream : ?Bool;
        stream_options : ?ChatCompletionStreamOptions;
        /// The suffix that comes after a completion of inserted text.  This parameter is only supported for `gpt-3.5-turbo-instruct`. 
        suffix : ?Text;
        /// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.  We generally recommend altering this or `top_p` but not both. 
        temperature : ?Float;
        /// An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.  We generally recommend altering this or `temperature` but not both. 
        top_p : ?Float;
        /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids). 
        user : ?Text;
    };

    // JSON sub-module: everything needed for JSON serialization
    public module JSON {
        // JSON-facing Motoko type: mirrors JSON structure
        // Named "JSON" to avoid shadowing the outer CreateCompletionRequest type
        public type JSON = {
            model : CreateCompletionRequestModel;
            prompt : CreateCompletionRequestPrompt;
            best_of : ?Int;
            echo : ?Bool;
            frequency_penalty : ?Float;
            logit_bias : ?Map<Text, Int>;
            logprobs : ?Int;
            max_tokens : ?Int;
            n : ?Int;
            presence_penalty : ?Float;
            seed : ?Int;
            stop : ?StopConfiguration;
            stream : ?Bool;
            stream_options : ?ChatCompletionStreamOptions;
            suffix : ?Text;
            temperature : ?Float;
            top_p : ?Float;
            user : ?Text;
        };

        // Convert User-facing type to JSON-facing Motoko type
        public func toJSON(value : CreateCompletionRequest) : JSON = {
            model = value.model;
            prompt = value.prompt;
            best_of = value.best_of;
            echo = value.echo;
            frequency_penalty = value.frequency_penalty;
            logit_bias = value.logit_bias;
            logprobs = value.logprobs;
            max_tokens = value.max_tokens;
            n = value.n;
            presence_penalty = value.presence_penalty;
            seed = value.seed;
            stop = value.stop;
            stream = value.stream;
            stream_options = value.stream_options;
            suffix = value.suffix;
            temperature = value.temperature;
            top_p = value.top_p;
            user = value.user;
        };

        // Convert JSON-facing Motoko type to User-facing type
        public func fromJSON(json : JSON) : ?CreateCompletionRequest {
            ?{
                model = json.model;
                prompt = json.prompt;
                best_of = do ? { let v = json.best_of!; if (v < 0) return null else Int.abs(v) };
                echo = json.echo;
                frequency_penalty = json.frequency_penalty;
                logit_bias = json.logit_bias;
                logprobs = do ? { let v = json.logprobs!; if (v < 0) return null else Int.abs(v) };
                max_tokens = do ? { let v = json.max_tokens!; if (v < 0) return null else Int.abs(v) };
                n = do ? { let v = json.n!; if (v < 0) return null else Int.abs(v) };
                presence_penalty = json.presence_penalty;
                seed = json.seed;
                stop = json.stop;
                stream = json.stream;
                stream_options = json.stream_options;
                suffix = json.suffix;
                temperature = json.temperature;
                top_p = json.top_p;
                user = json.user;
            }
        };
    }
}
