
import { type ChatCompletionStreamOptions; JSON = ChatCompletionStreamOptions } "./ChatCompletionStreamOptions";

import { type CreateCompletionRequestModel; JSON = CreateCompletionRequestModel } "./CreateCompletionRequestModel";

import { type CreateCompletionRequestPrompt; JSON = CreateCompletionRequestPrompt } "./CreateCompletionRequestPrompt";

import { type StopConfiguration; JSON = StopConfiguration } "./StopConfiguration";
import { type Map; entries; fromIter } "mo:core/pure/Map";
import Text "mo:core/Text";
import { Candid } "mo:serde-core";
import Array "mo:core/Array";
import List "mo:core/List";
import Float "mo:core/Float";
import Int "mo:core/Int";

// CreateCompletionRequest.mo

module {
    public type CreateCompletionRequest = {
        model : CreateCompletionRequestModel;
        prompt : ?CreateCompletionRequestPrompt;
        /// Generates `best_of` completions server-side and returns the \"best\" (the one with the highest log probability per token). Results cannot be streamed.  When used with `n`, `best_of` controls the number of candidate completions and `n` specifies how many to return – `best_of` must be greater than `n`.  **Note:** Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for `max_tokens` and `stop`. 
        best_of : ?Nat;
        /// Echo back the prompt in addition to the completion 
        echo : ?Bool;
        /// Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.  [See more information about frequency and presence penalties.](/docs/guides/text-generation) 
        frequency_penalty : ?Float;
        /// Modify the likelihood of specified tokens appearing in the completion.  Accepts a JSON object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this [tokenizer tool](/tokenizer?view=bpe) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.  As an example, you can pass `{\"50256\": -100}` to prevent the <|endoftext|> token from being generated. 
        logit_bias : ?Map<Text, Int>;
        /// Include the log probabilities on the `logprobs` most likely output tokens, as well the chosen tokens. For example, if `logprobs` is 5, the API will return a list of the 5 most likely tokens. The API will always return the `logprob` of the sampled token, so there may be up to `logprobs+1` elements in the response.  The maximum value for `logprobs` is 5. 
        logprobs : ?Nat;
        /// The maximum number of [tokens](/tokenizer) that can be generated in the completion.  The token count of your prompt plus `max_tokens` cannot exceed the model's context length. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens. 
        max_tokens : ?Nat;
        /// How many completions to generate for each prompt.  **Note:** Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for `max_tokens` and `stop`. 
        n : ?Nat;
        /// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.  [See more information about frequency and presence penalties.](/docs/guides/text-generation) 
        presence_penalty : ?Float;
        /// If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.  Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend. 
        seed : ?Int;
        stop : ?StopConfiguration;
        /// Whether to stream back partial progress. If set, tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://cookbook.openai.com/examples/how_to_stream_completions). 
        stream : ?Bool;
        stream_options : ?ChatCompletionStreamOptions;
        /// The suffix that comes after a completion of inserted text.  This parameter is only supported for `gpt-3.5-turbo-instruct`. 
        suffix : ?Text;
        /// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.  We generally recommend altering this or `top_p` but not both. 
        temperature : ?Float;
        /// An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.  We generally recommend altering this or `temperature` but not both. 
        top_p : ?Float;
        /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices#end-user-ids). 
        user : ?Text;
    };

    public module JSON {
        public func toCandidValue(value : CreateCompletionRequest) : Candid.Candid {
            let buf = List.empty<(Text, Candid.Candid)>();
            List.add(buf, ("model", CreateCompletionRequestModel.toCandidValue(value.model)));
            switch (value.prompt) {
                case (?v__) List.add(buf, ("prompt", CreateCompletionRequestPrompt.toCandidValue(v__)));
                case null ();
            };
            switch (value.best_of) {
                case (?v__) List.add(buf, ("best_of", #Nat(v__)));
                case null ();
            };
            switch (value.echo) {
                case (?v__) List.add(buf, ("echo", #Bool(v__)));
                case null ();
            };
            switch (value.frequency_penalty) {
                case (?v__) List.add(buf, ("frequency_penalty", #Float(v__)));
                case null ();
            };
            switch (value.logit_bias) {
                case (?v__) List.add(buf, ("logit_bias", #Record(Array.map<(Text, Int), (Text, Candid.Candid)>(Array.fromIter(entries(v__)), func((k, v) : (Text, Int)) : (Text, Candid.Candid) = (k, #Int(v))))));
                case null ();
            };
            switch (value.logprobs) {
                case (?v__) List.add(buf, ("logprobs", #Nat(v__)));
                case null ();
            };
            switch (value.max_tokens) {
                case (?v__) List.add(buf, ("max_tokens", #Nat(v__)));
                case null ();
            };
            switch (value.n) {
                case (?v__) List.add(buf, ("n", #Nat(v__)));
                case null ();
            };
            switch (value.presence_penalty) {
                case (?v__) List.add(buf, ("presence_penalty", #Float(v__)));
                case null ();
            };
            switch (value.seed) {
                case (?v__) List.add(buf, ("seed", #Int(v__)));
                case null ();
            };
            switch (value.stop) {
                case (?v__) List.add(buf, ("stop", StopConfiguration.toCandidValue(v__)));
                case null ();
            };
            switch (value.stream) {
                case (?v__) List.add(buf, ("stream", #Bool(v__)));
                case null ();
            };
            switch (value.stream_options) {
                case (?v__) List.add(buf, ("stream_options", ChatCompletionStreamOptions.toCandidValue(v__)));
                case null ();
            };
            switch (value.suffix) {
                case (?v__) List.add(buf, ("suffix", #Text(v__)));
                case null ();
            };
            switch (value.temperature) {
                case (?v__) List.add(buf, ("temperature", #Float(v__)));
                case null ();
            };
            switch (value.top_p) {
                case (?v__) List.add(buf, ("top_p", #Float(v__)));
                case null ();
            };
            switch (value.user) {
                case (?v__) List.add(buf, ("user", #Text(v__)));
                case null ();
            };
            #Record(List.toArray(buf));
        };

        public func fromCandidValue(candid : Candid.Candid) : ?CreateCompletionRequest =
            switch (candid) {
                case (#Record(fields)) {
                    let ?model_field = Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "model") else return null;
                    let ?model = (CreateCompletionRequestModel.fromCandidValue(model_field.1)) else return null;
                    let prompt : ?CreateCompletionRequestPrompt = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "prompt")) {
                        case (?prompt_field) (CreateCompletionRequestPrompt.fromCandidValue(prompt_field.1));
                        case null null;
                    };
                    let best_of : ?Nat = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "best_of")) {
                        case (?best_of_field) ((switch (best_of_field.1) { case (#Nat(n)) ?n; case (#Int(i)) (if (i < 0) null else ?Int.abs(i)); case _ null }));
                        case null null;
                    };
                    let echo : ?Bool = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "echo")) {
                        case (?echo_field) ((switch (echo_field.1) { case (#Bool(b)) ?b; case _ null }));
                        case null null;
                    };
                    let frequency_penalty : ?Float = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "frequency_penalty")) {
                        case (?frequency_penalty_field) ((switch (frequency_penalty_field.1) { case (#Float(f)) ?f; case (#Int(i)) ?Float.fromInt(i); case (#Nat(n)) ?Float.fromInt(n); case _ null }));
                        case null null;
                    };
                    let logit_bias : ?Map<Text, Int> = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "logit_bias")) {
                        case (?logit_bias_field) ((switch (logit_bias_field.1) {
                        case (#Record(pairs__)) {
                            let buf__ = List.empty<(Text, Int)>();
                            for ((k__, c__) in pairs__.values()) {
                                let ?v__ = (switch (c__) { case (#Int(j)) ?j; case (#Nat(k)) ?k; case _ null }) else return null;
                                List.add(buf__, (k__, v__));
                            };
                            ?fromIter<Text, Int>(List.toArray(buf__).values(), Text.compare);
                        };
                        case _ null;
                    }));
                        case null null;
                    };
                    let logprobs : ?Nat = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "logprobs")) {
                        case (?logprobs_field) ((switch (logprobs_field.1) { case (#Nat(n)) ?n; case (#Int(i)) (if (i < 0) null else ?Int.abs(i)); case _ null }));
                        case null null;
                    };
                    let max_tokens : ?Nat = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "max_tokens")) {
                        case (?max_tokens_field) ((switch (max_tokens_field.1) { case (#Nat(n)) ?n; case (#Int(i)) (if (i < 0) null else ?Int.abs(i)); case _ null }));
                        case null null;
                    };
                    let n : ?Nat = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "n")) {
                        case (?n_field) ((switch (n_field.1) { case (#Nat(n)) ?n; case (#Int(i)) (if (i < 0) null else ?Int.abs(i)); case _ null }));
                        case null null;
                    };
                    let presence_penalty : ?Float = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "presence_penalty")) {
                        case (?presence_penalty_field) ((switch (presence_penalty_field.1) { case (#Float(f)) ?f; case (#Int(i)) ?Float.fromInt(i); case (#Nat(n)) ?Float.fromInt(n); case _ null }));
                        case null null;
                    };
                    let seed : ?Int = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "seed")) {
                        case (?seed_field) ((switch (seed_field.1) { case (#Int(i)) ?i; case (#Nat(n)) ?n; case _ null }));
                        case null null;
                    };
                    let stop : ?StopConfiguration = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "stop")) {
                        case (?stop_field) (StopConfiguration.fromCandidValue(stop_field.1));
                        case null null;
                    };
                    let stream : ?Bool = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "stream")) {
                        case (?stream_field) ((switch (stream_field.1) { case (#Bool(b)) ?b; case _ null }));
                        case null null;
                    };
                    let stream_options : ?ChatCompletionStreamOptions = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "stream_options")) {
                        case (?stream_options_field) (ChatCompletionStreamOptions.fromCandidValue(stream_options_field.1));
                        case null null;
                    };
                    let suffix : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "suffix")) {
                        case (?suffix_field) ((switch (suffix_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let temperature : ?Float = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "temperature")) {
                        case (?temperature_field) ((switch (temperature_field.1) { case (#Float(f)) ?f; case (#Int(i)) ?Float.fromInt(i); case (#Nat(n)) ?Float.fromInt(n); case _ null }));
                        case null null;
                    };
                    let top_p : ?Float = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "top_p")) {
                        case (?top_p_field) ((switch (top_p_field.1) { case (#Float(f)) ?f; case (#Int(i)) ?Float.fromInt(i); case (#Nat(n)) ?Float.fromInt(n); case _ null }));
                        case null null;
                    };
                    let user : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "user")) {
                        case (?user_field) ((switch (user_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    ?{
                        model;
                        prompt;
                        best_of;
                        echo;
                        frequency_penalty;
                        logit_bias;
                        logprobs;
                        max_tokens;
                        n;
                        presence_penalty;
                        seed;
                        stop;
                        stream;
                        stream_options;
                        suffix;
                        temperature;
                        top_p;
                        user;
                    };
                };
                case _ null;
            };
    };
};
