/// Represents the content or the URL of an image generated by the OpenAI API.
import { Candid } "mo:serde-core";
import Array "mo:core/Array";
import List "mo:core/List";
import Float "mo:core/Float";
import Runtime "mo:core/Runtime";

// Image.mo

module {
    /// The required-fields slice of Image — what `init` consumes.
    /// Exposed so callers can write `let req : Required = {...}` if they want
    /// to manipulate the required-only payload independently of the full record.
    public type Required = {
    };

    // Optional-fields slice. Private — not part of the consumer surface;
    // it's an internal scaffold so we can express Image as an
    // `and`-intersection and keep `init` from listing every optional explicitly.
    type Optional = {
        b64_json : ?Text;
        url : ?Text;
        revised_prompt : ?Text;
    };

    public type Image = Required and Optional;

    public module JSON {
        // `init` constructs a Image from just its required fields,
        // defaulting all optional fields to `null`. Pair with record-update
        // syntax to layer in selected optionals:
        //   let req = { Image.init { …required fields… } with someOpt = ?… };
        // Implementation uses Candid round-trip — Candid record subtyping fills
        // absent optional fields with null. Costs a few cycles per call (init is
        // not on a hot path) but keeps generated code compact regardless of how
        // many optional fields the model has.
        public func init(required : Required) : Image {
            let ?res = from_candid(to_candid(required)) : ?Image else Runtime.unreachable();
            res
        };

        public func toCandidValue(value : Image) : Candid.Candid {
            let buf = List.empty<(Text, Candid.Candid)>();
            switch (value.b64_json) {
                case (?v__) List.add(buf, ("b64_json", #Text(v__)));
                case null ();
            };
            switch (value.url) {
                case (?v__) List.add(buf, ("url", #Text(v__)));
                case null ();
            };
            switch (value.revised_prompt) {
                case (?v__) List.add(buf, ("revised_prompt", #Text(v__)));
                case null ();
            };
            #Record(List.toArray(buf));
        };

        public func fromCandidValue(candid : Candid.Candid) : ?Image =
            switch (candid) {
                case (#Record(fields)) {
                    let b64_json : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "b64_json")) {
                        case (?b64_json_field) ((switch (b64_json_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let url : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "url")) {
                        case (?url_field) ((switch (url_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let revised_prompt : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "revised_prompt")) {
                        case (?revised_prompt_field) ((switch (revised_prompt_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    ?{
                        b64_json;
                        url;
                        revised_prompt;
                    };
                };
                case _ null;
            };
    };

    /// Re-export of `JSON.init` at the outer module level so callers using the
    /// whole-module import pattern (`import T "...";`) can write `T.init {…}`
    /// directly, mirroring the destructure-pattern (`{ type T; JSON = T }`)
    /// shorthand `T.init {…}` that resolves through the JSON alias.
    public let init = JSON.init;
};
