/// Represents the content or the URL of an image generated by the OpenAI API.
import { Candid } "mo:serde-core";
import Array "mo:core/Array";
import List "mo:core/List";
import Float "mo:core/Float";

// Image.mo

module {
    public type Image = {
        /// The base64-encoded JSON of the generated image. Default value for `gpt-image-1`, and only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.
        b64_json : ?Text;
        /// When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to `url` (default value). Unsupported for `gpt-image-1`.
        url : ?Text;
        /// For `dall-e-3` only, the revised prompt that was used to generate the image.
        revised_prompt : ?Text;
    };

    public module JSON {
        public func toCandidValue(value : Image) : Candid.Candid {
            let buf = List.empty<(Text, Candid.Candid)>();
            switch (value.b64_json) {
                case (?v__) List.add(buf, ("b64_json", #Text(v__)));
                case null ();
            };
            switch (value.url) {
                case (?v__) List.add(buf, ("url", #Text(v__)));
                case null ();
            };
            switch (value.revised_prompt) {
                case (?v__) List.add(buf, ("revised_prompt", #Text(v__)));
                case null ();
            };
            #Record(List.toArray(buf));
        };

        public func fromCandidValue(candid : Candid.Candid) : ?Image =
            switch (candid) {
                case (#Record(fields)) {
                    let b64_json : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "b64_json")) {
                        case (?b64_json_field) ((switch (b64_json_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let url : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "url")) {
                        case (?url_field) ((switch (url_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    let revised_prompt : ?Text = switch (Array.find<(Text, Candid.Candid)>(fields, func((k, _) : (Text, Candid.Candid)) : Bool = k == "revised_prompt")) {
                        case (?revised_prompt_field) ((switch (revised_prompt_field.1) { case (#Text(s)) ?s; case _ null }));
                        case null null;
                    };
                    ?{
                        b64_json;
                        url;
                        revised_prompt;
                    };
                };
                case _ null;
            };
    };
};
