/// Represents the content or the URL of an image generated by the OpenAI API.

// Image.mo

module {
    // User-facing type: what application code uses
    public type Image = {
        /// The base64-encoded JSON of the generated image. Default value for `gpt-image-1`, and only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.
        b64_json : ?Text;
        /// When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to `url` (default value). Unsupported for `gpt-image-1`.
        url : ?Text;
        /// For `dall-e-3` only, the revised prompt that was used to generate the image.
        revised_prompt : ?Text;
    };

    // JSON sub-module: everything needed for JSON serialization
    public module JSON {
        // JSON-facing Motoko type: mirrors JSON structure
        // Named "JSON" to avoid shadowing the outer Image type
        public type JSON = {
            b64_json : ?Text;
            url : ?Text;
            revised_prompt : ?Text;
        };

        // Convert User-facing type to JSON-facing Motoko type
        public func toJSON(value : Image) : JSON = value;

        // Convert JSON-facing Motoko type to User-facing type
        public func fromJSON(json : JSON) : ?Image = ?json;

        // Pre-flight validation (`diagnostics=true`): surface generator-known wire-format
        // gaps as `?Text`, so api.mustache can `throw Error.reject(msg)` instead of letting
        // bad JSON reach the upstream API and come back as an opaque 4xx.
        public func validate(_value : Image) : ?Text = null;
    }
}
